config/routes.rb
ConsumerApp::Application.routes.draw do

  root :to => "static_pages#home"

  resources :accounts 
  resources :mailboxes

  resources :employers do
    resources :mailboxes
    resources :job_postings
    member do 
      get :followme
    end
  end  

  resources :sponsors do 
  resources :mailboxes
    member do 
      get :followme
      get :jobsearch
      post :jobsearch
    end
  end  

  resources :candidates #, only: [:new, :create, :delete]

  resources :job_postings

  

  
  resources :sessions, only: [:new, :create, :destroy]

  get "static_pages/help"
  match "/signin", to: "sessions#new", via: "get"
  match "/signout", to: "sessions#destroy", via: "delete"
  match "/signup", to: "accounts#new", via: "get"

end

app/views/shared/_candidatesfeed.html.erb
	<% if @sponsor.candidates.any? %>

		<% @candidatesfeed.each do |post|  %>
	
			<li class="list-group-item <%= cycle("oddpost", "evenpost")%>" id="<%= post.id %>">
				<span class="user">
					<%= link_to candidate_path(post) do %>
					<h4><%= post.name %></h4>
					<% end %>
				</span>
				<span class="timestamp">
					 <%= post.city %>,<%= post.state %> - Posted <%= time_ago_in_words(post.created_at) %> ago. 
					| Trash it: <%= link_to "", post, method: :delete, data: { confirm: "Are you sure you want to delete '#{post.name}'? " }, title: post.name, class: "glyphicon glyphicon-trash" %>
				</span>
			</li>
		<% end %>
	<% end %>
	<%= will_paginate @candidatesfeed, renderer: BootstrapPagination::Rails  %>

app/views/shared/_candidatesfeed_item.html.erb
<li class="list-group-item <%= cycle("oddpost", "evenpost")%>" id="<%= candidatesfeed_item.id %>">

  <span class="content"><h2><%= link_to candidatesfeed_item.name, candidatesfeed_item.sponsor %></h2></span>
    <span class="user">
  Sponsor - <%=  candidatesfeed_item.sponsor.name %>,
  </span>
  <span class="timestamp">
    Updated <%= time_ago_in_words(candidatesfeed_item.created_at) %> ago.
  </span>
  <span class="delete">
  <% if current_user?(@sponsor) %>
  <%= link_to "|Delete|", candidatesfeed_item, method: :delete, confirm: "Are you sure?", name: candidatesfeed_item.bio %>
  <% end %>
  </span>

</li>

app/views/shared/_contactsfeed.html.erb
<% if current_user.follow_count > 0 %>
  <ul class="list-group">
    <%= render partial: 'shared/contactsfeed_item', collection: @candidatesfeed_items %><br/>
  </ul>
<% end %>

app/views/shared/_contactsfeed_item.html.erb
<li class="list-group-item <%= cycle("oddpost", "evenpost")%>" id="<%= contactsfeed_item.id %>">

  <span class="content"><h2><%= link_to candidatesfeed_item.name, candidatesfeed_item.sponsor %></h2></span>
    <span class="user">
  Sponsor - <%=  candidatesfeed_item.sponsor.name %>,
  </span>
  <span class="timestamp">
    Updated <%= time_ago_in_words(candidatesfeed_item.created_at) %> ago.
  </span>
  <span class="delete">
  <% if current_user?(@account) %>
  <%= link_to "|Delete|", candidatesfeed_item, method: :delete, confirm: "Are you sure?", name: candidatesfeed_item.bio %>
  <% end %>
  </span>

</li>

app/views/shared/_error_messages.html.erb
<% if awesomeobject.errors.any? %> 
  <div id="error_explanation">
    <div class="alert alert-error">
      Sorry, please fix the following <%= pluralize(awesomeobject.errors.count, "form error") %>.
    </div>
    <ul>
    <% awesomeobject.errors.full_messages.each do |msg| %>
      <li>*<%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_jobpostfeed.html.erb
<% if @jobpostfeed_items.any? %>
  <ul class="list-group">
    <%= render partial: 'shared/jobpostfeed_item', collection: @jobpostfeed_items %><br/>
  </ul>
  <%= will_paginate @jobpostfeed_items %>
<% end %>

app/views/shared/_jobpostfeed_item.html.erb
<li class="list-group-item <%= cycle("oddpost", "evenpost")%>" id="<%= jobpostfeed_item.id %>">
  <span class="user">
	<%=  jobpostfeed_item.employer.name %>:
  </span>
  <span class="content"><h2><%= link_to jobpostfeed_item.title, employer_job_postings_path(current_user) %></h2></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(jobpostfeed_item.created_at) %> ago.
  </span>
</li>