config/routes.rb
ConsumerApp::Application.routes.draw do

  root :to => "static_pages#home"

  resources :accounts 
  resources :mailboxes

  resources :employers do
    resources :mailboxes
    resources :job_postings
    member do 
      get :followme
    end
  end  

  resources :sponsors do 
  resources :mailboxes
    member do 
      get :followme
      get :jobsearch
      post :jobsearch
    end
  end  

  resources :candidates #, only: [:new, :create, :delete]

  resources :job_postings

  

  
  resources :sessions, only: [:new, :create, :destroy]

  get "static_pages/help"
  match "/signin", to: "sessions#new", via: "get"
  match "/signout", to: "sessions#destroy", via: "delete"
  match "/signup", to: "accounts#new", via: "get"

end

app/models/sponsor.rb
class Sponsor < Account

	has_many :candidates, dependent: :destroy
	
	accepts_nested_attributes_for :candidates

	acts_as_messageable

	#this was not in, and everything seemed to still work.
  	acts_as_followable
  	acts_as_follower




def mailboxer_email(object)
	return nil
end



 #  	def following?(other_user)
 #  		self.relationships.find_by_followed_id(other_user.id)  
 #  	end


	# def follow!(other_user)
	# 	self.relationships.create!(followed_id: other_user.id)
	# end

	# def unfollow!(other_user)
	# 	self.relationships.find_by_followed_id(other_user.id).destroy
	# end

end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController


	before_action :signed_in_user, only: [:edit, :update, :index, :destroy, :following, :followers] 
	before_action :correct_account,  only: [:edit, :update] 

	# def index
	# 	@sponsor = Sponsor.all
	# end

	# def new
	# 	@sponsor = Sponsor.new
	# end

	def show
		if signed_in?
			@sponsor = Sponsor.find(params[:id])
			@candidatesfeed_items = @sponsor.candidates.paginate(page: params[:page])
			@candidatesfeed = @sponsor.candidates.paginate(page: params[:page], per_page: 5)
			@currentusermailbox = @sponsor.mailbox.inbox.paginate(page: params[:mailbox], per_page: 5)
			@currentusersentbox = @sponsor.mailbox.sentbox.paginate(page: params[:sentbox], per_page: 5)

			if params[:searchjobs] != nil
				@query = params[:searchjobs]
			else 
				@query = " "
			end

			@jobsearchresults = []
			unless params[:searchjobs].nil? || params[:searchjobs].strip.empty?
				@search = JobPosting.search {fulltext params[:searchjobs]}
				@jobsearchresults = @search.results
			end
			@jobsearchresults
		end
	end

	def edit
		@sponsor = Sponsor.find(params[:id])
	end


	def update
		if @sponsor.update_attributes(account_new_params)
			flash[:success] = "Profile updated"
			redirect_to @sponsor
		else
			render 'edit'
		end
	end


	# def followthis
	# 	@find_account = Sponsor.find_by(email: params[:session][:email].downcase)
	# 	redirect_to @sponsor
	# end


	def followme 
		search = params[:search]
		@user = Account.find_by(email: search)

	  if current_user

	    if current_user == @user
			flash[:error] = "You cannot follow yourself."
			redirect_to sponsor_path(current_user)

		elsif @user == nil
			flash[:error] = "#{search} E-mail could not be found, please make sure that they are signed up!".html_safe
			redirect_to sponsor_path(current_user)

		elsif current_user.following?(@user) == true
			flash[:error] = "You are already following #{search}".html_safe
			redirect_to sponsor_path(current_user)

	    else
			current_user.follow(@user)
			# RecommenderMailer.new_follower(@sponsor).deliver if @sponsor.notify_new_follower
			flash[:success] = "You are now following #{@user.name}."
			redirect_to sponsor_path(current_user)
	    end
	  else
		redirect_to(root_url) 
	  end
	end

	# def search
	# 	q = params[:user][:email]
	# 	@users = Sponsor.find(:all, :conditions => ["name LIKE %?%",q])
	# end



	def store_location  # => a.k.a. store_location
		session[:return_to] = request.url if request.get?  #request is a special object that gets the URL of the requested page.
	end

	def signed_in_user
		unless signed_in?
			store_location
			redirect_to signin_path, notice: "Please sign in first, thank you!"
		end
	end


	private

		def account_new_params # =>  INSTEAD OF User.new(params[:user]), allows only certain params to go through
			params.require(:sponsor).permit(:name, :email, :password, :password_confirmation, :type)
		end

		def correct_account 
			@sponsor = Sponsor.find(params[:id])
			redirect_to(root_url) unless current_user?(@sponsor)
		end

end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/views/sponsors/_sponsor_page.html.erb
<div class="col-md-9 col-md-offset-2">
	<div class="col-md-9 col-md-offset-0">

			<div class="page-header">
			<h1><%= "Updates from #{@sponsor.name.capitalize}" %></h1>
			<h3><small><%=  link_to "<- Back to my profile", account_path(current_user) %></small></h3>
			</div>

	<div class="panel panel-default panel-primary">
        <div class="panel-heading">
        	<%= "#{@sponsor.name.capitalize}'s Canidates Listing" %>
        </div>
    	<ul class="list-group">
        	<% if @sponsor.candidates.any? %>

				<% @candidatesfeed.each do |post|  %>
			
					<li class="list-group-item <%= cycle("oddpost", "evenpost")%>" id="<%= post.id %>">
						<span class="user">
							<%= link_to candidate_path(post) do %>
							<h4><%= post.name %></h4>
							<% end %>
						</span>
						<span class="timestamp">
							<%= post.city %>,<%= post.state %> - Posted <%= time_ago_in_words(post.created_at) %> ago. 
						</span>
					</li>
				<% end %>
			<% end %>
			<%= will_paginate @candidatesfeed, renderer: BootstrapPagination::Rails  %>
		</ul>
    </div>
</div>

app/views/sponsors/edit.html.erb
<%= provide(:title, "Update Profile - #{@sponsor.name}") %>

		<div class="row-fluid">
		<div class="col-md-6 col-md-offset-3">
			<h1>Update your profile</h1> <br/>
			<%= form_for(@sponsor, :html => { class: "form-horizontal", role: "form" } ) do |f| %>
				<%= render 'shared/error_messages', awesomeobject: @sponsor %>

  				<div class="form-group">
					<%= f.label :name, :class => "col-sm-2 control-label" %>
					<div class="col-sm-10">
						<%= f.text_field :name, class: "form-control", placeholder: "Name" %>
					</div>
				</div>

  				<div class="form-group">
					<%= f.label :email, :class => "col-sm-2 control-label" %>
					<div class="col-sm-10">
						<%= f.text_field :email, class: "form-control", placeholder: "E-mail" %>
					</div>
				</div>		


  				<div class="form-group">
					<%= f.label :password, :class => "col-sm-2 control-label" %>
					<div class="col-sm-10">
						<%= f.password_field :password, class: "form-control", placeholder: "Password" %>
					</div>
				</div>


  				<div class="form-group">
					<%= f.label :password_confirmation, :class => "col-sm-2 control-label" %>
					<div class="col-sm-10">
						<%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Password" %>
					</div>
				</div>

  				<div class="form-group">
					<div class="col-sm-offset-2 col-sm-10">
						<%= f.submit "Update my account", class: "btn btn-large btn-primary" %>
					</div>
				</div>

			<% end %>

		</div>
	</div>

app/views/sponsors/show.html.erb
<%= provide(:title, "Profile - #{@sponsor.name}") %>

<% if signed_in? && current_user?(@sponsor)%>
<div class="row-fluid">
	<div class="col-md-2 col-md-offset-2">
		<ul class="nav nav-pills nav-stacked">
			<li class="active">
				<a href="#">
				Messages<span class="badge pull-right"> <%= message_count(current_user) %> </span> 
				<!-- @account.messages  -->
				</a>
			</li>
			<li class="active">
				<%= link_to sponsor_path(current_user) do %>
				Contacts <span class="badge pull-right"><%= current_user.follow_count %></span> 
				<% end %>
				<!-- @account.messages  -->
			</li>
			<li class="active">
				<%= link_to edit_sponsor_path(@sponsor) do %>
				Edit My Info <span class="badge pull-right"></span> 
				<% end %>
				<!-- @account.messages  -->
			</li>
			<li class="active">
				<%= link_to new_candidate_path do %>
				Add Candidate (<%= @candidatesfeed_items.count %>)<span class="badge pull-right"></span> 
				<% end %>
				<!-- @account.messages  -->
			</li>
		</ul>
	</div>

	<div class="col-md-6 col-md-offset-0">
		<h2><small>Search Jobs by City (Paid Node with Solr Search is not online)</small></h2> 

		<%= form_tag sponsor_path, :method => 'get' do %>
			<div class="form-group">
				<%= text_field_tag :searchjobs, params[:searchjobs], :class => 'form-control', :placeholder => 'Enter City Name i.e. modesto' %>
			</div>
			<%= submit_tag "Search", :name => nil ,:class => 'btn btn-default"' %>
		<% end %>
		<br/>
		<% if !@jobsearchresults.empty? && !params[:searchjobs].blank? %>
			<div class="panel panel-default panel-primary">
	        	<div class="panel-heading">
	        		<%= "Job Search Results for #{@jobsearchresults.first.city}. . ." %>
	        	</div>
        		<ul class="list-group">
					<% for result in @jobsearchresults %>
					<li class="list-group-item">
						<%= link_to result do %>
							<%= result.title %>
						<% end %>
						<div class="pull-right">
							Posted <%= time_ago_in_words(result.created_at) %> ago.
						</div>
					 </li>
					<% end %>	
        		</ul>
			</div>
		<% elsif @jobsearchresults.empty? && !@query.blank? %>
			<div class="panel panel-default panel-primary">
		        <div class="panel-heading">
		        	Job Search Results. . .
		        </div>
				<ul class="list-group">
					<li class="list-group-item">	
							No job postings found in that city.
					</li>
	        	</ul>
			</div>
		<% end %>

		<br/>
		<div class="panel panel-default panel-primary">
	        <div class="panel-heading">
	        	Your Posted Candidates
	        	<%= link_to new_candidate_path, class: "white-font" do %>
	        	<p class="pull-right">
	        		<span class="glyphicon glyphicon-plus-sign"></span>&nbsp; Add Candidate
	        	</p>
	        	<% end %>
	        </div>

	    	<ul class="list-group">
		        <li class="list-group-item"><%= render 'shared/candidatesfeed' %></li>
	        </ul>
        </div>

		<div class="panel panel-default panel-primary">
	        <div class="panel-heading">
	        	My Contacts	  (Try adding demo@example.com)    
					<%= form_tag followme_sponsor_path, :method => 'get', :class => 'navbar-form navbar-right addbox'  do %>
						<div class="form-group">
							<%= text_field_tag :search, params[:search], :class => 'form-control', :placeholder => 'Add by E-mail' %>
						</div>
						<%= submit_tag "Add Contact", :name => nil , :class => 'btn btn-default black-text' %>
					<% end %>      	
	        	<p class="pull-right">
	        		<span class="glyphicon glyphicon-plus-sign"></span>
	        	</p>
	        </div>
	    	<ul class="list-group">
				<div>
					<% current_user.all_following.each do |user| %>
							<li class="list-group-item">
								<span>
									<% if user.type == "Employer" %>
										<%= link_to employer_path(user.id) do %>
										<%= user.name %>
										<% end %>
									<% elsif user.type == "Sponsor" %>
										<%= link_to sponsor_path(user.id) do %>
										<%= user.name %>
										<% end %>									
									<% end %>
								</span>
								<span class="pull-right">
									<% if user.type == "Employer" && user.job_postings.any? %>
										 <%= user.job_postings.last.title %>, added <%= time_ago_in_words(user.job_postings.last.created_at) %> ago.
									<% elsif user.type == "Sponsor" && user.candidates.any? %>
										added <%= user.candidates.last.name %>, <%= time_ago_in_words(user.candidates.last.created_at) %> ago.
									<% else %>
										No activity yet!
									<% end %>
								</span>
							</li>
					<% end %>
				</div>
	        </ul>
        </div>
		<div class="row-fluid">
			<div class="col-md-9 col-md-offset-2">
				<div class="page-header">
				<h3><small>Communications</small></h3>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row-fluid">
	<div class="col-md-6 col-md-offset-4">
        <div class="panel panel-default panel-primary">
	        <div class="panel-heading">
	        	Received Messages 
	        </div>
        	<ul class="list-group">
			<% if has_message?(current_user) %>
				<% @currentusermailbox.each do |message_attribute| %>
				<% @message_attributes = { name: message_attribute.originator.name, body: message_attribute.original_message.body, subject: message_attribute.original_message.subject, created_at: message_attribute.original_message.created_at} %>
				<li class="list-group-item <%= cycle("oddpost-mailbox", "evenpost")%>" id="<%= message_attribute.id %>"> 
					<h4><small><%= "Received From:" %></small><small class="black-text"><%= " #{@message_attributes[:name] }" %></small></small><small> (<%= "#{time_ago_in_words(@message_attributes[:created_at]) } ago" %>)</small></h4>
					<h4><small><%= "Subject:" %></small><small class="black-text"><%= " #{@message_attributes[:subject] }" %></small></h4>
					<div class="glyphicon glyphicon-forward"></div> <%= "#{@message_attributes[:body]}" %>
				</li>
				<% end %> 
				<%= will_paginate @currentusermailbox, :param_name => 'mailbox', renderer: BootstrapPagination::Rails  %>
			<% end %>
			</ul>
        </div>
        <div class="panel panel-default panel-primary">
	        <div class="panel-heading">
	        	Sent Messages<br/><br/>
	        	<p class="pull-right">
	        		<div class="form-group">
	        		<%= form_tag({controller: "mailboxes", action: "create"}, method: :post) do %>
					<br/>Select From The List Of People You Are Following:<br/>
					<%= select_tag :recipient_id , options_from_collection_for_select(current_user.all_following, :id , :name, class: "black-text" ) %>
					<br/>Subject:<br/>
					<%= text_field_tag :subject %>
					<br/>Message:<br/>
					<%= text_area_tag :body %>
					<%= submit_tag 'Send Message', class: "black-text" %>
					<% end %>
					</div>
	        	</p>
			</div>

        	<ul class="list-group">
			<% if has_message?(current_user) %>
				<% @currentusersentbox.each do |message_attribute| %>
				<% @message_attributes = { name: message_attribute.participants.second.name, body: message_attribute.original_message.body, subject: message_attribute.original_message.subject, created_at: message_attribute.original_message.created_at } %>
				<li class="list-group-item <%= cycle("oddpost-sentbox", "evenpost")%>" id="<%= message_attribute.id %>">
					<h4><small><%= "Sent to:" %></small><small class="black-text"><%= " #{@message_attributes[:name] }" %></small><small> (<%= "#{time_ago_in_words(@message_attributes[:created_at]) } ago" %>)</small></h4>
					<h4><small><%= "Subject:" %></small><small class="black-text"><%= " #{@message_attributes[:subject] }" %></small></h4>
					<div class="glyphicon glyphicon-forward"></div> <%= "#{@message_attributes[:body]}" %>
				</li>
				<% end %> 
				<%= will_paginate @currentusersentbox, :param_name => 'sentbox', renderer: BootstrapPagination::Rails  %>
			<% end %>
			</ul>
        </div>
	</div>
</div>

<% elsif signed_in? %>

<div class="row-fluid">
	<%= render 'sponsor_page' %>
</div>

<% else %>
<div class="row-fluid">
	<div class="col-md-9 col-md-offset-4">
		<h1>You must sign in to view the complete profile</h1>
	</div>
</div>
<% end %>