config/routes.rb
ConsumerApp::Application.routes.draw do

  root :to => "static_pages#home"

  resources :accounts 
  resources :mailboxes

  resources :employers do
    resources :mailboxes
    resources :job_postings
    member do 
      get :followme
    end
  end  

  resources :sponsors do 
  resources :mailboxes
    member do 
      get :followme
      get :jobsearch
      post :jobsearch
    end
  end  

  resources :candidates #, only: [:new, :create, :delete]

  resources :job_postings

  

  
  resources :sessions, only: [:new, :create, :destroy]

  get "static_pages/help"
  match "/signin", to: "sessions#new", via: "get"
  match "/signout", to: "sessions#destroy", via: "delete"
  match "/signup", to: "accounts#new", via: "get"

end

app/views/layouts/_footer.html.erb
<div class="row-fluid">
  <div class="col-md-9 col-md-offset-2">
    <footer>
    	<small>
      	Copyright 2014 - Zubair Desai
      </small>
      </small>
        <nav>
          <ul>
            <li><%= link_to "About", "#" %></li>
            <li><%= link_to "Contact", "#" %></li>
          </ul>
        </nav>
      </small>
    </footer>
  </div>
</div

app/views/layouts/_header.html.erb
<div class="row-fluid">
	<div class="col-md-9 col-md-offset-2">
		<nav class="navbar navbar-default" role="navigation">
		  <!-- Brand and toggle get grouped for better mobile display -->
		  	<div class="navbar-header">
		    	<%= link_to "Consumer App", root_path, class: "navbar-brand" %>
		  	</div>
		  	<div class="collapse navbar-collapse  pull-right" id="bs-example-navbar-collapse-1">
			    <ul class="nav navbar-nav">
			      	<li class="#{is_active?(static_pages_help_path)}"><a href="#">Help</a></li>
			      <!-- <li><a href="#">Sign in</a></li> -->
					<% if signed_in? && employer_user? %>	
						<li class="<%= "#{is_active?(employer_path(current_user))}"%>"><%= link_to "My Profile", employer_path(current_user) , class: "navbar-link" %></li>
					<% elsif signed_in? && sponsor_user? %>	
						<li class="<%= "#{is_active?(sponsor_path(current_user))}"%>"><%= link_to "My Profile", sponsor_path(current_user) , class: "navbar-link" %></li>
					<% end %> 
					<% if signed_in? && employer_user? %>			
						<li class="<%= "#{is_active?(edit_employer_path(current_user))}"%>"><%= link_to "Settings", edit_employer_path(current_user), class: "navbar-link" %></li>
					<% elsif signed_in? && sponsor_user? %>			
						<li class="<%= "#{is_active?(edit_sponsor_path(current_user))}"%>"><%= link_to "Settings", edit_sponsor_path(current_user), class: "navbar-link" %></li>
					<% end %> 
					<% if signed_in? %>
						<li class="<%= "#{is_active?(signout_path)}" %>"> <%= link_to "Log out (#{current_user.name})", signout_path, { method: "delete", class: "navbar-link"} %></li>
					<% else %>
						<li class="<%= "#{is_active?(signin_path)}"%>"><%= link_to "Sign in", signin_path %></li>
					<% end %>
			 	</ul>
			</div>
		</nav>
	</div>
</div>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=  full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true  %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>

	<%= render 'layouts/header' %>

	<div class="row-fluid">
		<div class="col-md-9 col-md-offset-2">
			<% flash.each do |key, value| %>
		    	<h1><div class="alert alert-<%= key %>"><%= value %></div></h1>
		    <% end %>
		</div>
	</div>

	<%= yield %>
	<%= render 'layouts/footer' %>

<div class="row-fluid">
	<div class="col-md-9 col-md-offset-2">
		<%= debug(params) if Rails.env.development? %>
	</div>
</div>

</body>
</html>